// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs3eVFTZY3pJLIZHGpvSaBjsVdKnUJrug',
    appId: '1:210621730821:web:c67b66491d19740749cc6c',
    messagingSenderId: '210621730821',
    projectId: 'ultra-climber-430614-t8',
    authDomain: 'ultra-climber-430614-t8.firebaseapp.com',
    storageBucket: 'ultra-climber-430614-t8.appspot.com',
    measurementId: 'G-189NH3FDY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBouu3fODs6LEZmOGRenqa___Zc-VGUp8A',
    appId: '1:210621730821:android:a034101ab420835749cc6c',
    messagingSenderId: '210621730821',
    projectId: 'ultra-climber-430614-t8',
    storageBucket: 'ultra-climber-430614-t8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVCtC3XjTX0HjfcHm4iABdRprs8gJPWtQ',
    appId: '1:210621730821:ios:35901d7f43b028c049cc6c',
    messagingSenderId: '210621730821',
    projectId: 'ultra-climber-430614-t8',
    storageBucket: 'ultra-climber-430614-t8.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVCtC3XjTX0HjfcHm4iABdRprs8gJPWtQ',
    appId: '1:210621730821:ios:35901d7f43b028c049cc6c',
    messagingSenderId: '210621730821',
    projectId: 'ultra-climber-430614-t8',
    storageBucket: 'ultra-climber-430614-t8.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs3eVFTZY3pJLIZHGpvSaBjsVdKnUJrug',
    appId: '1:210621730821:web:9d261f98142fb1df49cc6c',
    messagingSenderId: '210621730821',
    projectId: 'ultra-climber-430614-t8',
    authDomain: 'ultra-climber-430614-t8.firebaseapp.com',
    storageBucket: 'ultra-climber-430614-t8.appspot.com',
    measurementId: 'G-TY83H878L1',
  );
}
